### PR TITLE
Add cadair.theme meta file

### PR DESCRIPTION
**Pull request by Kwpolska**
Hi there,
this PR adds a .theme meta file, for the use of Nikola and the new themes.getnikola.com site.

On a side note, could we please take the theme and put it in the `getnikola/nikola-themes` repo, instead of using a submodule? It would make maintenance easier for us.

### CODE REVIEW

**Comment by Cadair** [comment]
@Kwpolska I would be happy for you to move this into the theme repository.

**Comment by Kwpolska** [comment]
@Cadair Thanks!

**Comment by Cadair** [comment]
@Kwpolska let me know when you have pulled it in, and I will push a commit here saying that it has been moved.

**Comment by Kwpolska** [comment]
Done: https://github.com/getnikola/nikola-themes/commit/d4587ac54ef05c4b4b69cf19dbfc982b5641971a

**Pull request merged**
